# Generated by Django 4.2.27 on 2025-12-19 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rhema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu de la Parole')),
                ('verse', models.CharField(max_length=255, verbose_name='Référence Biblique')),
                ('published_at', models.DateField(default=django.utils.timezone.now, help_text='Le Rhema sera affiché à cette date précise.', verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pastor', models.ForeignKey(limit_choices_to={'role__in': ['PASTOR', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='rhemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rhema',
                'verbose_name_plural': 'Rhemas',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
