# Generated by Django 4.2.27 on 2025-12-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhema',
            name='meditation',
            field=models.TextField(blank=True, null=True, verbose_name='Méditation / Note du Pasteur'),
        ),
    ]
