# Generated by Django 4.2.27 on 2026-01-13 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rhema', '0002_rhema_meditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rhema',
            name='pastor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['PASTOR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rhemas', to=settings.AUTH_USER_MODEL),
        ),
    ]
