# Generated by Django 4.2.27 on 2025-12-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name="Date de l'événement")),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Image/Affiche')),
                ('is_annual', models.BooleanField(default=False, verbose_name='Événement annuel')),
                ('is_past', models.BooleanField(default=False, verbose_name='Événement passé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Titre de la photo')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Photo')),
                ('caption', models.TextField(blank=True, verbose_name='Légende')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo de la galerie',
                'verbose_name_plural': 'Photos de la galerie',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WHO_WE_ARE', 'Qui sommes-nous'), ('HISTORY', 'Historique / Notre Histoire'), ('MISSIONS', 'Missions & Vision')], max_length=20, unique=True, verbose_name='Type de section')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name="Image d'illustration")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Section d'information",
                'verbose_name_plural': "Sections d'information",
            },
        ),
    ]
