# Generated by Django 4.2.27 on 2025-12-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('title', models.CharField(help_text='Ex: Pasteur Fondateur, Visionnaire', max_length=255, verbose_name='Titre / Fonction')),
                ('biography', models.TextField(verbose_name='Biographie')),
                ('history', models.TextField(verbose_name='Historique personnel / Vision')),
                ('photo', models.ImageField(upload_to='visionaries/', verbose_name='Photo officielle')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Lien Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Lien Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Lien Twitter (X)')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Lien YouTube Personnel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif (Visible sur le site)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visionnaire',
                'verbose_name_plural': 'Visionnaires',
            },
        ),
    ]
