# Generated by Django 4.2.27 on 2025-12-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_visionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure'),
        ),
    ]
