# Generated by Django 4.2.27 on 2026-01-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_event_category_event_location_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Épinglé en haut'),
        ),
    ]
