# Generated by Django 4.2.27 on 2026-01-12 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(verbose_name='Date souhaitée')),
                ('requested_time', models.TimeField(verbose_name='Heure souhaitée')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé'), ('COMPLETED', 'Terminé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet du rendez-vous')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Détails')),
                ('pastor_notes', models.TextField(blank=True, verbose_name='Notes du Pasteur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_member', to=settings.AUTH_USER_MODEL)),
                ('pastor', models.ForeignKey(limit_choices_to={'role': 'PASTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_pastor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-requested_date', '-requested_time'],
            },
        ),
        migrations.CreateModel(
            name='PastorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Lundi'), ('TUESDAY', 'Mardi'), ('WEDNESDAY', 'Mercredi'), ('THURSDAY', 'Jeudi'), ('FRIDAY', 'Vendredi'), ('SATURDAY', 'Samedi'), ('SUNDAY', 'Dimanche')], max_length=10, verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pastor', models.ForeignKey(limit_choices_to={'role': 'PASTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilité du Pasteur',
                'verbose_name_plural': 'Disponibilités du Pasteur',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('pastor', 'day_of_week', 'start_time')},
            },
        ),
    ]
