# Generated by Django 4.2.27 on 2026-01-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(blank=True, help_text='Lieu physique ou lien de visio', max_length=255, verbose_name='Lieu / Lien'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='message_to_member',
            field=models.TextField(blank=True, help_text='Instructions ou message pour le membre', verbose_name='Message pour le membre'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pastor_notes',
            field=models.TextField(blank=True, verbose_name='Notes pour le Pasteur (privé)'),
        ),
    ]
