# Generated by Django 4.2.27 on 2026-01-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+90 533 874 86 46', max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(default='contact@cyprusforchrist.com', max_length=254, verbose_name='Email')),
                ('address', models.TextField(default='Turgut hasan sokak no 2, Kucuk kaymakli, Lefkosa, Chypre du Nord', verbose_name='Adresse')),
                ('service_times_sunday', models.CharField(default='Dimanche: 17h15', max_length=100, verbose_name='Service du Dimanche')),
                ('service_times_wednesday', models.CharField(default='Mercredi: 17h15', max_length=100, verbose_name='Service du Mercredi')),
                ('whatsapp', models.CharField(default='905338748646', max_length=100, verbose_name='WhatsApp')),
                ('instagram', models.URLField(default='https://www.instagram.com/cyprusforchrist', verbose_name='Instagram')),
                ('youtube', models.URLField(default='https://m.youtube.com/@CyprusForChrist01', verbose_name='YouTube')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informations de contact',
                'verbose_name_plural': 'Informations de contact',
            },
        ),
    ]
