# Generated by Django 4.2.27 on 2025-12-19 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Nom complet')),
                ('title', models.CharField(max_length=255, verbose_name='Sujet de prière')),
                ('content', models.TextField(verbose_name='Contenu de la requête')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PRAYED', 'Soutenu en prière'), ('RESOLVED', 'Exaucé / Résolu')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Rester anonyme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requête de prière',
                'verbose_name_plural': 'Requêtes de prière',
                'ordering': ['-created_at'],
            },
        ),
    ]
