# Generated by Django 4.2.27 on 2025-12-19 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('paypal_payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID Paiement PayPal')),
                ('paypal_payer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Payeur PayPal')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Don anonyme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-created_at'],
            },
        ),
    ]
