# Generated by Django 4.2.27 on 2026-01-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Projet'),
        ),
    ]
