# Generated by Django 4.2.27 on 2025-12-19 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Lien YouTube')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='sermons/pdfs/', verbose_name='Fichier PDF')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='sermons/covers/', verbose_name='Image de couverture')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pastor', models.ForeignKey(limit_choices_to={'role__in': ['PASTOR', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sermon',
                'verbose_name_plural': 'Sermons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SermonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sermons.sermon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire de sermon',
                'verbose_name_plural': 'Commentaires de sermons',
                'ordering': ['-created_at'],
            },
        ),
    ]
