# Generated by Django 4.2.27 on 2026-01-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_sermon_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='category',
            field=models.CharField(choices=[('SUNDAY_SERVICE', 'Culte Dimanche'), ('BIBLE_STUDY', 'Étude Biblique'), ('YOUTH', 'Jeunesse'), ('CONFERENCE', 'Conférence'), ('WORSHIP', 'Louange'), ('OTHER', 'Autre')], default='SUNDAY_SERVICE', max_length=20, verbose_name='Catégorie'),
        ),
    ]
