# Generated by Django 4.2.27 on 2025-12-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('PASTOR', 'Pasteur'), ('MODERATOR', 'Modérateur'), ('MEMBER', 'Membre')], default='MEMBER', max_length=20, verbose_name='Rôle'),
        ),
    ]
