# Generated by Django 4.2.27 on 2026-01-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_address_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('code', models.CharField(max_length=6, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Code de réinitialisation',
                'verbose_name_plural': 'Codes de réinitialisation',
                'ordering': ['-created_at'],
            },
        ),
    ]
